### PR TITLE
Fix typo

### LINKED ISSUE #45: Minor typo in folder name and checks page
- In the Checks page, when you have the option to create a new check, "Grafana" is misspelled
image
- The dashboard folder is currently named "SyntheticMonitoring" without a space
image

### PR DESCRIPTION
**Pull request by mem**
Fixes #45

Signed-off-by: Marcelo E. Magallon <marcelo.magallon@grafana.com>

### CODE REVIEW

File: src/dashboards/loader.ts [hunk 1]
```diff
@@ -13,13 +13,13 @@ async function findSyntheticMonitoringFolder(): Promise<FolderInfo> {
   const backendSrv = getBackendSrv();
   const folders = (await backendSrv.get(`api/folders`)) as FolderInfo[];
   for (const folder of folders) {
-    if (folder.title === 'SyntheticMonitoring') {
+    if (folder.title === 'Synthetic Monitoring') {
```
Comment (mem) [inline src/dashboards/loader.ts:16]: any strong feelings about *not* renaming the existing (if any) folder?

Comment (electron0zero) [reply src/dashboards/loader.ts:16]: IMO with space looks better :thinking:
