### PR TITLE
fix: increase job name length limit

### LINKED ISSUE #75: Check job name length limit is restrictive
The current length limit for a check job name is 32 characters, which feels restrictive.

### PR DESCRIPTION
**Pull request by rdubrock**
Fixes #75 

In addition to increasing the job name limit, this PR adds some text truncation and a view dashboard button in the list view.

### CODE REVIEW

File: src/components/CheckListItem/CheckItemActionButtons.tsx [hunk 1]
```diff
@@ -47,8 +47,10 @@ export const CheckItemActionButtons = ({ check, showViewDashboard, onRemoveCheck
 
   return (
     <ButtonGroup className={styles.actionButtonGroup}>
-      {showViewDashboard && (
-        <Button onClick={() => showDashboard(check, checkType)} size="sm" variant="link">
+      {viewDashboardAsIcon ? (
+        <IconButton name="apps" onClick={showDashboard} />
```
Comment (samjewell) [inline src/components/CheckListItem/CheckItemActionButtons.tsx:51]: Is this attr `name="apps"` actually used anywhere? And should it be `name="dashboard"` or something instead?
I'm still learning my way around, so I might be looking in the wrong place, but I was expecting to find this `name` attr or something similar rendered directly into the DOM, onto this element.

File: src/components/CheckListItem/CheckItemActionButtons.tsx [hunk 2]
```diff
@@ -17,17 +17,17 @@ const getStyles = (theme: GrafanaTheme) => ({
...
 
-export const CheckItemActionButtons = ({ check, showViewDashboard, onRemoveCheck }: Props) => {
+export const CheckItemActionButtons = ({ check, viewDashboardAsIcon, onRemoveCheck }: Props) => {
   const styles = useStyles(getStyles);
   const [showDeleteModal, setShowDeleteModal] = useState(false);
   const checkType = getCheckType(check.settings);
   const { instance } = useContext(InstanceContext);
 
-  const showDashboard = (check: Check, checkType: CheckType) => {
+  const showDashboard = () => {
```
Comment (samjewell) [inline src/components/CheckListItem/CheckItemActionButtons.tsx:30]: Nice change here ❤️

**Review by samjewell — COMMENTED** [review]
This looks nice to me 👍 , great change Russ. I've just asked one question in the comments.
Quick question: How do you switch an org from the old interface to the new one, for the checks page? Thanks 🙏
