### PR TITLE
fix: allow hostnames that start with a number and have a subdomain

### LINKED ISSUE #193: Validation issues for HTTP urls with a number
HTTP urls that include `www` and have a hostname that start with a number are being flagged as invalid, when they should be considered valid. 

examples:

`https://www.1foo.com`

### PR DESCRIPTION
**Pull request by rdubrock**
Fixes #193 

Screen Shot 2021-02-08 at 1 22 35 PM

### CODE REVIEW

**Comment by mem** [comment]
FYI, this is the validation happening in the API: https://github.com/grafana/synthetic-monitoring-agent/blob/41c479d968c5b09da826f74c2ef666ddf423879d/pkg/pb/synthetic_monitoring/checks_extra.go#L420

Each component of the FQHN must be 1 <= len <= 63, and each component must start and end with a digit or a letter, except for the last one which must contain a letter somewhere.

The total length of the FQHN (including dots) must be 1 <= len <= 255.

File: src/validation.ts [hunk 1]
```diff
@@ -248,7 +248,7 @@ function validateHostname(target: string): string | undefined {
   const ipv6 = new Address6(target);
   const pc = punycode.toASCII(target);
   // note that \w matches "_"
-  const re = new RegExp(/^[a-z0-9]([-a-z0-9]{0,62}[a-z0-9])?(\.[a-z]([-a-z0-9]{0,62}[a-z0-9])?)+$/, 'i');
+  const re = new RegExp(/^[a-z0-9]([-a-z0-9]{0,62}[a-z0-9])?(\.[a-z0-9]([-a-z0-9]{0,62}[a-z0-9])?)+$/, 'i');
```
Comment (mem) [inline src/validation.ts:251]: I think this should reject FQHN where the TLD part is all numbers:

```
^[a-z0-9]([-a-z0-9]{0,62}[a-z0-9])?(\.[a-z0-9]([-a-z0-9]{0,62}[a-z0-9])?)*\.([a-z]|[a-z0-9]([-a-z0-9]{0,62}[a-z])|[a-z]([-a-z0-9]{0,62}[a-z0-9])?)$
```
