### PR TITLE
fix: handle a breaking change in the alerting api for grafana v9

### LINKED ISSUE #467: Alerting view is showing an error in Grafana v9
Navigating to the alerts tab in Grafana v9 results in an error

Screen Shot 2022-06-09 at 08 42 54

### PR DESCRIPTION
**Pull request by rdubrock**
Fixes #467

### CODE REVIEW

File: src/hooks/useAlerts.ts [hunk 1]
```diff
@@ -76,11 +77,11 @@ const legacyFetchSMRules = (alertRulerUrl: string): Promise<RuleResponse> =>
       return { rules: [], error: e.data?.message ?? 'We ran into a problem and could not fetch the alert rules' };
     });
 
-const fetchSMRules = (metricInstanceId: number): Promise<RuleResponse> =>
+const fetchSMRules = (metricIdentifier: string | number): Promise<RuleResponse> =>
```
Comment (thepalbi) [inline src/hooks/useAlerts.ts:80]: nit: `metricInstanceIdentifier` since it's the id for a metrics souce?

**Review by thepalbi — APPROVED** [review]
LGTM, just one nit
